### ISSUE TITLE
Connection with remote DB

### ISSUE THREAD

**Issue by Mahmoudgarwallane** [ClementG63/Neo4Driver#2]
Hey awesome people, 
I've discovered your package and I'm so grateful.
I used it with a local database, It worked fine, But I tried implementing it with a remote database (Aura DB),
and I had multiple error.
My questions are :
 - does this package support connections with remote DBs
 - If so how can I do that
 
 Thank you very much, I really appreciate your work

**Comment by 9clg6** [comment]
I've never tried it with Aura DB so it doesn't surprise me that it doesn't work, it didn't fit my original need but I'll look into it and deploy a fix when a solution is found. 

Thanks for your involvement!

UPDATE: Neo4J uses his own security protocol, "neo4j+s://" then we can't use HTTP request.

**Comment by Mahmoudgarwallane** [comment]
I've asked in Neo4J's community  about this and they suggested to use graphQl with AuraDB and they said that it works perfectly fine with flutter.
thank you so much Clement for your response and the work you're doing is amazing !!

**Comment by 9clg6** [comment]
This is a good news !
If you have any suggestions to improve the package, don't hesitate to submit them to me by making MR / fork :)

And leave a little ⭐️ it's always nice 🫶

Thanks
