### ISSUE TITLE
dart sdk 2.18 not supported

### ISSUE THREAD

**Issue by ghost** [ClementG63/Neo4Driver#3]
Hi there, I have dart SDK 2.18 installed. This package requires dart SDK  >=1.0.0 <2.0.0.

`The current Dart SDK version is 2.18.6. Because my_first_app depends on neo4dart any which requires SDK version >=1.0.0 <2.0.0, version solving failed.`

**Comment by 9clg6** [comment]
It works for me in 2.18.5
