### ISSUE TITLE
Understanding: How to properly start a Neo4j database

### ISSUE THREAD

**Issue by Gene-Dana** [ClementG63/Neo4Driver#5]
Hi there 👋🏼 I really appreciate the work you put into making this ! 

My team and I are seeking to utilize this package with dart frog and we're unsure how to start the database! Is this something we do programmatically in dart? Or elsewhere?

From what I understand, this package assumes that Neo4j is already running locally

**Comment by 9clg6** [comment]
First of all I am glad you like my work!

To start an instance of a Neo4J database you have to create it from the desktop application or from the CLI.
My package does not allow to start an instance, only to manipulate it (CRUD functions)

⭐️⭐️

**Comment by Gene-Dana** [comment]
I really appreciate your feedback ! I know it seemed obvious and I was unsure how to work everything together because I'm also very new to Docker.

And... your comment helped me better understand the Docker documentation and the approach ! Thank you !

<img width="922" alt="image" src="https://user-images.githubusercontent.com/45580241/213730313-ff717d20-a06b-4932-99b9-f525e164951f.png">
https://docs.docker.com/get-started/07_multi_container/
