### ISSUE TITLE
[Appreciate and Request] Customize the charset

### ISSUE THREAD

**Issue by CorvusYe** [ClementG63/Neo4Driver#9]
Hi @ClementG63 
First of all, thank you for developing a great project and doing open source.

Make a request, when we call _executePostRequest or _executePostRequestWithAuthorization, 
it may be better to specify the character set.

**Comment by 9clg6** [comment]
Hello ! First of all thanks for your suggestion.

According to the [doc](https://pub.dev/documentation/http/latest/http/post.html), the default encoding is utf8. Unless you want to specify a different encoding I think we can leave UTF-8. Do you need to change it ?

**Comment by CorvusYe** [comment]
Thanks for the reply.

I also use UTF-8. But it doesn't seem to work as expected.
When I set the character set for `Response`, the problem disappears.

```dart
    Response response =
        await ce.executeQuery(method: HTTPMethod.post, query: query);

    // The key line:
    response.headers['content-type'] = 'application/json;charset=UTF-8'; 

    dynamic body = decoder.convert(response.body);
```

Before:

![image](https://user-images.githubusercontent.com/15630211/218694452-02c6d52b-cae7-49c9-9376-d3926caa0206.png)

After:

![image](https://user-images.githubusercontent.com/15630211/218695712-b2e702f7-b3f2-4dff-b6a7-b46bed2e1c53.png)

**Comment by 9clg6** [comment]
Ok then I can modify it.

**Comment by 9clg6** [comment]
You can try branch fix/charset_parameter and tell me if it works. Else I set encoding in headers.

**Comment by CorvusYe** [comment]
It occured again.
This `encoding` in post method should be the encoding of the request, but not the response.

**Comment by 9clg6** [comment]
I updated the branch fix/charset_parameter by adding response interceptor, where you can update headers. Should fix your error. 

Check parameter "customInterceptor" in neo_service.dart

Sorry for delay

**Comment by CorvusYe** [comment]
Seems like an elegant solution. I'll try again tomorrow. Thanks for the contribution.

**Comment by CorvusYe** [comment]
The problem I encountered has been solved. Thanks again.
